### PR TITLE
Add SOCRATESSingleColumnForcings dependecny

### PR DESCRIPTION
**Pull request by trontrytel**
This PR adds SOCRATESSingleColumnForcings to the dependecies in `test`, `integration_tests` and `perf` folders. 

It also imports the package into `tc_driver/Cases.jl` and `tc_driver/initial_condition.jl`.

This is done in preparation for  https://github.com/CliMA/TurbulenceConvection.jl/pull/1325

### CODE REVIEW

**Comment by trontrytel** [comment]
Looks like it worked. I just need to add the new dependency to the `docs` folder too. I'll fix that and merge. And then we can rebase the actual SOCRATES PR @jbphyswx

**Review by jbphyswx — COMMENTED** [review]
seems fine, though idk the specifics about what we want in the manifests, or if we'll actually need SSCF in initial_conditions.jl -- seems that was a drybubble specific thing.

**Comment by trontrytel** [comment]
> seems fine, though idk the specifics about what we want in the manifests, or if we'll actually need SSCF in initial_conditions.jl -- seems that was a drybubble specific thing.

The manifests are fine in this PR. I wanted to do it separately to make your PR smaller and handle the dependency change separately.

I added SOCRATES to `initial_conditions` just to make sure that you can use it. Feel free to delete it from there in your PR if it turns out to be not needed.

**Comment by trontrytel** [comment]
I can update to Julia 1.8.5 and see if I can do the same dependency update but with fewer patch changes tomorrow. Feel free to beat me to it @jbphyswx if you have the time. But I would suggest first adding the SOCRATES package to our repo and then rebasing your PR and seeing if it works

**Comment by trontrytel** [comment]
Closing in favor of https://github.com/CliMA/TurbulenceConvection.jl/pull/1328

**Pull request closed without merging**
