### PR TITLE
trying to bring back the truncated gcm mesh

### PR DESCRIPTION
**Pull request by trontrytel**
# PULL REQUEST

## Purpose and Content
(Clearly and concisely state the purpose of this PR)

## Benefits and Risks
(State concisely the benefits to be derived from and the risks associated with this PR)

## Linked Issues
(Provide references to any link issues. Use closes #issuenum to automatically close an open issue)
- Fixes #
- Closes #

## PR Checklist
- [ ] This PR has a corresponding issue OR is linked to an SDI.
- [ ] I have followed CliMA's codebase [contribution](https://clima.github.io/ClimateMachine.jl/latest/Contributing/) and [style](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) guidelines OR N/A.
- [ ] I have followed CliMA's [documentation policy](https://github.com/CliMA/policies/wiki/Documentation-Policy).
- [ ] I have checked all issues and PRs and I certify that this PR does not duplicate an open PR.
- [ ] I linted my code on my local machine prior to submission OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code used in an integration test OR N/A.
- [ ] All tests ran successfully on my local machine OR N/A.
- [ ] All classes, modules, and function contain docstrings OR N/A.
- [ ] Documentation has been added/updated OR N/A.

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
Can we split out the manifest changes?

**Comment by trontrytel** [comment]
> Can we split out the manifest changes?

I think I can delete all the manifest changes. They are not needed for this PR at all

**Comment by trontrytel** [comment]
@charleskawczynski  - the problem with this PR is that the TC grid that is returned from the truncated option is 3 points too short (according to @ilopezgp )

**Comment by charleskawczynski** [comment]
> @charleskawczynski - the problem with this PR is that the TC grid that is returned from the truncated option is 3 points too short (according to @ilopezgp )

This is definitely puzzling. The PR looks fine. I can try taking a look in the afternoon. Maybe I'll try adding back in so we can compare notes?

**Comment by trontrytel** [comment]
Done via https://github.com/CliMA/TurbulenceConvection.jl/pull/1233#event-7043247727

**Pull request closed without merging**
