### PR TITLE
Fix timeseries IO, theta-var branch

### PR DESCRIPTION
**Pull request by ilopezgp**
Fixes timeseries IO, syncing it with profiles IO.

Adds tests to check for fill values.

In order to merge this PR, I changed all performance benchmarks to using a single time step. Otherwise they broke for some reason. All case runs in the test suite ran smoothly.

This is the theta-var version of #1095 .

### CODE REVIEW

**Comment by ilopezgp** [comment]
bors try

**Comment by ilopezgp** [comment]
Do you know what's going on with the performance tests here @charleskawczynski ?

**Comment by charleskawczynski** [comment]
> Do you know what's going on with the performance tests here @charleskawczynski ?

I don't know what's going on with the precompilation speed up tests, but the benchmark step one was somewhat fixed by #1083.

**Comment by ilopezgp** [comment]
> > Do you know what's going on with the performance tests here @charleskawczynski ?
> 
> I don't know what's going on with the precompilation speed up tests, but the benchmark step one was somewhat fixed by #1083.

I tried implementing the changes from #1083 in a new commit, and I still get all the performance issues from before, including benchmark_step!

**Comment by ilopezgp** [comment]
bors try

**Pull request merged**
