### PR TITLE
bump version for new release

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
We shouldn't fix / close #936 first, should we?

**Comment by trontrytel** [comment]
> We shouldn't fix / close #936 first, should we?

I wanted to run some calibrations with multiple updrafts, so a release would be nice :) 

Do we know how to fix #936? Or do we want to remove those tests from the CI until we fix them?

**Comment by charleskawczynski** [comment]
> I wanted to run some calibrations with multiple updrafts, so a release would be nice :)

Sounds good to me.

> Do we know how to fix #936? Or do we want to remove those tests from the CI until we fix them?

We need a namelist that doesn't result in things crashing.

**Comment by trontrytel** [comment]
> We need a namelist that doesn't result in things crashing.

ok - that can mean anything from 5 minutes to "2 weeks". I'm gonna merge it in.

**Pull request merged**
