### PR TITLE
Add linear entrainment closure

### PR DESCRIPTION
**Pull request by costachris**
Add linear model for entrainment/detrainment closure, using Relu to ensure positivity.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
There are some minor issues with type stability, but we can fix that later. Overall LGTM

**Comment by costachris** [comment]
> There are some minor issues with type stability, but we can fix that later. Overall LGTM. Is this exercised at all? I'm starting to wonder if we should add more jobs with closures in active development.

It's not exercised by default, you have to set the namelist flag for `entrainment` to `Linear`. By jobs do you mean CI tests to see if the closure works before merging?

**Comment by charleskawczynski** [comment]
> > There are some minor issues with type stability, but we can fix that later. Overall LGTM. Is this exercised at all? I'm starting to wonder if we should add more jobs with closures in active development.
> 
> @charleskawczynski It's not exercised by default, you have to set the namelist flag for `entrainment` to `Linear`. By jobs do you mean CI tests to see if all the closures works before merging?

Yes, exactly. I guess it's fine if it's not exercised by our CI. Do you know if there are plans to add them at some point? Or is this still experimental? I'll think about this a bit more. Overall, I think it's fine to merge

**Comment by costachris** [comment]
> > > There are some minor issues with type stability, but we can fix that later. Overall LGTM. Is this exercised at all? I'm starting to wonder if we should add more jobs with closures in active development.
> > 
> > 
> > @charleskawczynski It's not exercised by default, you have to set the namelist flag for `entrainment` to `Linear`. By jobs do you mean CI tests to see if all the closures works before merging?
> 
> Yes, exactly. I guess it's fine if it's not exercised by our CI. Do you know if there are plans to add them at some point? Or is this still experimental? I'll think about this a bit more. Overall, I think it's fine to merge

I'd say it's still experimental until each method is calibrated, but it would be nice to have CI tests at that point so we can switch between them for comparison. 

I'll merge this after #732 and modify it to align with the changes made in that PR.

**Review by haakon-e — APPROVED** [review]
great work!

**Pull request merged**
