### PR TITLE
+0.0.1 to TC.jl version, update deps to julia 1.7.2

### PR DESCRIPTION
**Pull request by trontrytel**
I have:
- bumped `TC.jl` version: `0.17.0` -> `0.17.1`
- run `.dev/up_deps.jl` with julia version `1.7.2`

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
LGTM. I just cleared the depot and I'll try to r+ after it's finished.

**Comment by trontrytel** [comment]
Keeping fingers crossed

**Comment by charleskawczynski** [comment]
🤞🏻

**Pull request merged**
