### PR TITLE
add more parameters for calibration

### PR DESCRIPTION
**Pull request by trontrytel**
This PR adds more parameters for calibration. It requires CLIMAParameters v0.4.3 (the new patch release).

For future reference, the correct workflow to merge this is to: 
1) open a separate PR with up_deps
2) clear the depot for the CI
3) bump version (it's a breaking change since now we are only compatible with the new version of CP.jl)
4) merge
5) tag a new release.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
Open an `up_deps.jl` PR first, then rebase/merge this

**Comment by ilopezgp** [comment]
After this is merged, let's do a breaking release please, not a patch

**Comment by trontrytel** [comment]
> After this is merged, let's do a breaking release please, not a patch

Yes I agree. It was a patch release for CLIMAParameters, because I was only extending the list of parameters. (So no breaking changes for its users downstream).

The changes proposed in this PR are only compatible with the new version of CLIMAParameters. So it is a breaking change for TC.jl

**Comment by charleskawczynski** [comment]
Actually, I don't think a rebase is needed. Let's try

**Comment by trontrytel** [comment]
bors try

**Pull request merged**
