### PR TITLE
Add reference state profile plots to docs

### PR DESCRIPTION
**Pull request by charleskawczynski**
This will be helpful to verify that the reference state profiles don't change too dramatically in #25.

### CODE REVIEW

**Review by haakon-e — APPROVED** [review]
It seems like the bottom and left sides of the figures don't fit the documentation frame, i.e. the plot labels are slightly hidden. Otherwise, looks good.

**Comment by charleskawczynski** [comment]
Yeah, let me see if I can fix that

**Comment by charleskawczynski** [comment]
Thanks for taking a look!

**Pull request merged**
