### PR TITLE
set default dt = 10sec and dt=3 in deep convection

### PR DESCRIPTION
**Pull request by yairchn**

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by yairchn** [comment]
Bors r+

**Comment by yairchn** [comment]
Bors r+

**Comment by yairchn** [comment]
Bors r+

**Comment by charleskawczynski** [comment]
What's going on with the mean temperature at TOA in Rico?

**Comment by charleskawczynski** [comment]
(not a blocker, it's just surprising to see changes there just from changing the timestep)

**Comment by yairchn** [comment]
Bors r-

**Comment by yairchn** [comment]
Bors r+

**Pull request merged**
