### PR TITLE
use latent heat const with T

### PR DESCRIPTION
**Pull request by trontrytel**
As discussed today, to be consistent with the definition of `theta_liq_ice` we should use constant latent heat.

### CODE REVIEW

**Comment by trontrytel** [comment]
Curious how this will affect the plots...

**Comment by charleskawczynski** [comment]
Ah, I think we need to bump Thermodynamics.jl, too, so that we update to the new version

**Comment by yairchn** [comment]
> Curious how this will affect the plots...

Not sure what scares me more, that it would effect the plots, or that it would not effect them ....

**Comment by trontrytel** [comment]
> Ah, I think we need to bump Thermodynamics.jl, too, so that we update to the new version

Right!

**Review by ilopezgp — APPROVED** [review]

**Review by charleskawczynski — APPROVED** [review]

**Review by yairchn — APPROVED** [review]

**Review by charleskawczynski — COMMENTED** [review]
We could add type casting for type stability, but we can leave it for now and do a type-stability sprint sometime in the future.

**Pull request merged**
