### PR TITLE
Apply some bug fixes

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR applies some bug fixes to bugs found in #218. I think this needs careful review.

### CODE REVIEW

**Comment by yairchn** [comment]
you left a comment that 
'f_rad_dual = dual_faces(self.f_rad, grid, k + 1)'
should be 
'f_rad_dual = dual_faces(self.f_rad, grid, k)'

if you implement it ql_mean in decoms looks better even though you should mind the oscillations in updraft_w contour plot
see the ' yc/dycoms_bug ' branch

**Comment by charleskawczynski** [comment]
Yeah, that's a good point, maybe they were two bugs counter-acting each other. Trying to fix both together...

**Comment by yairchn** [comment]
> Yeah, that's a good point, maybe they were two bugs counter-acting each other. Trying to fix both together...

yes check the decoys figures for ' yc/dycoms_bug '

**Comment by charleskawczynski** [comment]
Interestingly, both together look better than either separately. Not sure if these changes are acceptable, though.

This would now close #213.

**Comment by yairchn** [comment]
> Interestingly, both together look better than either separately. Not sure if these changes are acceptable, though.
> 
> This would now close #213.

yeh, I think these results are ok, the oscillations in updraft_w are strange though

**Comment by charleskawczynski** [comment]
Merging and opening an issue about the oscillations.

**Comment by charleskawczynski** [comment]
Closes #213

**Pull request merged**
