### PR TITLE
Upgrade to julia 1.8

### PR DESCRIPTION
**Pull request by charleskawczynski**
Upgrade to julia 1.8

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Yikes, Soares completely breaks (`DomainError`) when only upgrading to julia 1.8

**Comment by yairchn** [comment]
> Yikes, some cases are having serious issues when only upgrading to julia 1.8:
> 
> * Soares (breaks with `DomainError`)
> * Nieuwstadt (breaks with `DomainError`)
> * GABLS (not breaking but _very_ different looking results)
> 
> @yairchn, any commonalities that you see between these cases? Any hints will help track down what's going off the rails here

are you also upgrading surface fluxes? there is an issue there I'm trying to solve

**Comment by charleskawczynski** [comment]
> are you also upgrading surface fluxes? there is an issue there I'm trying to solve

Ah! good catch!

**Pull request merged**
