### PR TITLE
unify timesteps in the model

### PR DESCRIPTION
**Pull request by yairchn**
This PR unifies the time steps in the model across the updrafts and the grid mean the environment and the microphysics. The tilmestep is set to 3 sec which works. Next step would be to add a CFL condition that combines updraft velocity and rainfall velocity to get the optimal tilmestep. 

** behavioral changes !! ** 

take a close look

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Can we update the description? #115 shrunk the timestep, and this is just removing substepping, correct? Also, we should rebase because I just fixed a bug in #127--we previously were not comparing with tc main (we are now, though), we were stuck comparing against an older commit.

**Review by charleskawczynski — APPROVED** [review]
The results seem virtually unchanged, so LGTM. @trontrytel, I'm not sure that the rain part is exercised yet, do these code changes look okay?

**Comment by trontrytel** [comment]
LGTM too. Lets merge it. Precipitation was never tested and fully integrated into scampy. So whatever this PR changes, I will have to deal with after I'm done switching to TD.jl

**Comment by charleskawczynski** [comment]
@yairchn let’s rebase/squash first, then merge

**Comment by yairchn** [comment]
Bors r+

**Pull request merged**
