### PR TITLE
Add internal clima parameters

### PR DESCRIPTION
**Pull request by trontrytel**
As suggested by Issue https://github.com/CliMA/TurbulenceConvection.jl/issues/997 this adds `InternalClimaParams.jl` as a way to interface with the default parameters of CliMA. The already existing `ClimaParameters.jl` file (with experimental params that are not yet part of CliMAParameters) is now renamed to `ExperimentalClimaParams.jl`.

HTH with moving parameters around!

### CODE REVIEW

**Comment by odunbar** [comment]
Just to be clear - this is something which will improve the **current** CLIMAParameters interface only, it is (I believe) incompatable with the new interface. 

So It would be good to have this on the parts of the code which are not currently being worked on (e.g. those parts-outside of EDMF) only - as there we have already effectively completed the transition.

**Comment by trontrytel** [comment]
> Just to be clear - this is something which will improve the **current** CLIMAParameters interface only, it is (I believe) incompatable with the new interface.
> 
> So It would be good to have this on the parts of the code which are not currently being worked on (e.g. those parts-outside of EDMF) only - as there we have already effectively completed the transition.
> 
> My concern is that the parameter boxes are built hierarchically currently.

Did not mean to step on someone elses PR. I thought, as suggested by @charleskawczynski, that this makes the move easier because it limits the needed changes to one file only. 

I thought that `InternalClimaParams.jl` file can still be populated based on the parameter boxes and the structure you are introducing? But feel free to close the PR if it's going in the wrong direction.

**Comment by charleskawczynski** [comment]
@odunbar and I chatted. This PR is compatible, but we'll also need to add a few methods for hiding the structure of the outer-most parameter boxes. Something like:

```julia
thermo_params(ps::EarthParameterSet) = ps # which will become ps.thermo_params
microphys_params(ps::EarthParameterSet) = ps # which will become ps.microphys_params
surf_fluxes_params(ps::EarthParameterSet) = ps # which will become ps.surf_fluxes_params
```

We can do the methods in a separate PR.

**Review by charleskawczynski — APPROVED** [review]

**Comment by trontrytel** [comment]
Sounds good. It would be sad not to merge a PR with such a momentous number. 

I'll rebase and merge this then ;)

**Pull request merged**
