### PR TITLE
pass precip_model via simulation1d

### PR DESCRIPTION
**Pull request by yairchn**
I am not sure how to properly move the definitions of `AbstractPrecipitationModel` out of src, 
@charleskawczynski ?
Otherwise this I think is a start for defining microphysics independently of the EDMF model

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Review by trontrytel — APPROVED** [review]

**Comment by yairchn** [comment]
Bors r+

**Comment by yairchn** [comment]
Bors r+

**Comment by charleskawczynski** [comment]
We need to fix the box and sphere cases

**Comment by yairchn** [comment]
Bors r+

**Comment by yairchn** [comment]
Bors r+

**Comment by charleskawczynski** [comment]
Why is this PR now reverting recent 3d bomex work?

**Comment by charleskawczynski** [comment]
Thanks!

**Comment by yairchn** [comment]
Bors r+

**Comment by yairchn** [comment]
bots r+

**Comment by charleskawczynski** [comment]
> bots r+

🤖

**Comment by yairchn** [comment]
Bors r+

**Pull request merged**
