### PR TITLE
Add most missing pieces from theta-var.

### PR DESCRIPTION
**Pull request by ilopezgp**
# PULL REQUEST

## Purpose and Content

- Merges #1217 to main branch,
- Merges #1229 to main branch,
- Adds back the `calibrate_io` clause, which seems to have been deleted. Was this intentional @charleskawczynski ? Are we missing it in other parts of the code?

## Benefits and Risks

- Benefit: Potentially return to the main branch for research purposes.

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
> Was this intentional

No, I think the IO refactoring (to allow for adding the sphere test case) were pretty large and complicated, so I probably removed that by accident

**Comment by ilopezgp** [comment]
> > Was this intentional
> 
> No, I think the IO refactoring (to allow for adding the sphere test case) were pretty large and complicated, so I probably removed that by accident

Sounds good! Let's see if this works

**Comment by ilopezgp** [comment]
@charleskawczynski it seems like I need to convert the new diagnostics to `Duals` to be able to write them to file, any idea how to do this?

```


│   exception =
--
  | │    MethodError: no method matching write_ts(::Array{NetCDFIO_Stats{Float64}, 3}, ::String, ::Float64)
  | │    Closest candidates are:
  | │      write_ts(::Any, ::Any, ::ForwardDiff.Dual) at /central/scratch/esm/slurm-buildkite/turbulenceconvection-ci/11549/turbulenceconvection-ci/driver/NetCDFIO.jl:160
```

**Pull request merged**
