### PR TITLE
fix: LES_driven_SCM & DryBubble default namelist

### PR DESCRIPTION
**Pull request by haakon-e**
fixes bugs introduced in #1251 and #34

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
Ouch, this looks like it may have taken a while to track down. How is #34 related?

If we fix #908, we'd be able to write a pretty nice / simple log to show users which variables have been changed.

**Comment by haakon-e** [comment]
According to git blame, it was in #34 the changes (bug) in DryBubble was introduced.

**Comment by haakon-e** [comment]
I agree we should get to #908 (alternatively by finishing up CliMA parameters integration). 

From the point of view of calibration, we are in fact assuming that all parameter names are unique, regardless of which part of the name list it is located.

**Comment by charleskawczynski** [comment]
> According to git blame, it was in #34 the changes (bug) in DryBubble was introduced.

Ah, yeah, I missed the dry bubble one. Good catch!

**Review by ilopezgp — APPROVED** [review]
LGTM

**Comment by ilopezgp** [comment]
Should we merge @haakon-e ?

**Comment by haakon-e** [comment]
> Should we merge @haakon-e ?

Yes. I'm travelling currently so haven't been able to get around to fix the deps, etc. but can try to get around to this soon

**Comment by ilopezgp** [comment]
@haakon-e just a reminder!

**Review by ilopezgp — APPROVED** [review]

**Pull request merged**
