### PR TITLE
Clean up, document LES driven forcing.

### PR DESCRIPTION
**Pull request by ilopezgp**
I removed a few unused lines of code, improved naming of the tendencies and defined what these tendencies are following Shen et al (2021).

### CODE REVIEW

**Comment by ilopezgp** [comment]
I am a bit lost with the error messages here.

**Review by charleskawczynski — APPROVED** [review]
Code changes seem fine to me.

**Comment by ilopezgp** [comment]
> Code changes seem fine to me.

Do you know what is causing the tests to fail? It seems to be during plotting.

**Comment by trontrytel** [comment]
> > Code changes seem fine to me.
> 
> Do you know what is causing the tests to fail? It seems to be during plotting.

Looks like some NaNs:

https://github.com/CliMA/TurbulenceConvection.jl/runs/4095155991?check_suite_focus=true#step:5:554

Probably unrelated to this PR, because I'm seeing the same error in mine

**Pull request merged**
