### PR TITLE
Remove some TC. calls in driver

### PR DESCRIPTION
**Pull request by yairchn**
In this PR I have moved the initialization of EDMF variables into src while concentrating them in a 'initialize_turbconv' for a single call in driver. In the future 'initialize_turbconv' could be dispatched for EDMF or another model

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Why do the mse tables change?

**Comment by yairchn** [comment]
> Why do the mse tables change?

now they are not changed

**Comment by charleskawczynski** [comment]
I guess this is fine, I still don't really understand why we want to put ICs / case-specific code inside src/

**Comment by ilopezgp** [comment]
I don't think this should be in source

**Pull request closed without merging**
