### PR TITLE
Squeeze out space in profile plots

### LINKED ISSUE #124: Improve profile plots
After #116, the profiles plots have relatively large margins, and all the xlabels/ylabels are repeated for each plot, which takes up room that could otherwise make the plots themselves bigger.

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR updates the layout of the profile plots to squeeze out the lost white space. I also changed the layout to be 5 columns (it was previously 4). We can change it back if people prefer 4, most of the gained space was in the horizontal direction, so I think this actually preserves the look of the figures over sticking with 4, but I have no strong feelings about this.

Closes #124.

### CODE REVIEW

**Comment by haakon-e** [comment]
Could you add a top-level title which states which simulation case the subplots are showing? e.g. "Bomex contours", etc.

Also, I think we should consider making all plots larger (extend width & height). If I zoom in to study details of one profile, it becomes apparent that the resolution could be improved.
image
In safari, this also seems to be maximum zoom level.
I realize you may have chosen this size to fit all subplots in a typical browser window, but I'm not sure if this is strictly necessary.

**Review by haakon-e — APPROVED** [review]
Other than that, LGTM!

**Comment by charleskawczynski** [comment]
Ahhh, I see what you mean, we’ll need to increase the size and font size, since increasing the size has the effect of making the font look smaller. I’ll try this out soon

**Comment by charleskawczynski** [comment]
Alright, updated! Would be nice to hear feedback on these changes when people get a chance. I think it's looking near complete 🚀

**Comment by haakon-e** [comment]
Seems like you need to pass through the case name to the plotting functions.

**Comment by charleskawczynski** [comment]
> Seems like you need to pass through the case name to the plotting functions.

Whoops, updated, hopefully this works.

**Comment by charleskawczynski** [comment]
Going to merge this for now. I think we can do tweaking beyond this if people wish.

**Pull request merged**
