### PR TITLE
lets see if it helps CI

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Review by charleskawczynski — COMMENTED** [review]
Perhaps this identifies that it is related to qi (and the use of strings, here). I'll keep digging into this to see what's going on. Feel free to close

**Comment by trontrytel** [comment]
> Perhaps this identifies that it is related to qi (and the use of strings, here). I'll keep digging into this to see what's going on. Feel free to close

Sounds good. But in case this issue with CI slows down other PRs, I'm ok with merging it for now. And coming back to plotting qi later.

**Comment by charleskawczynski** [comment]
Fair point.

**Pull request merged**
