### PR TITLE
Make CFL computation based on local dz

### PR DESCRIPTION
**Pull request by charleskawczynski**
Between this PR and #669 (and fixing up the indefinite integrals), we should be ready to stretch the grid.

### CODE REVIEW

**Comment by yairchn** [comment]
There is an unused dz here 
https://github.com/CliMA/TurbulenceConvection.jl/blob/25457ecfbbeb030193b778f057ead1e48b17fc04/driver/initial_conditions.jl#L91

**Comment by yairchn** [comment]
one inverse here
https://github.com/CliMA/TurbulenceConvection.jl/blob/25457ecfbbeb030193b778f057ead1e48b17fc04/src/Turbulence_PrognosticTKE.jl#L348

**Comment by yairchn** [comment]
Not sure about this one 
https://github.com/CliMA/TurbulenceConvection.jl/blob/25457ecfbbeb030193b778f057ead1e48b17fc04/test/clima_core_extensions.jl#L64

**Comment by yairchn** [comment]
there are some in 'compute_diagnostics.jl' here 
https://github.com/CliMA/TurbulenceConvection.jl/blob/25457ecfbbeb030193b778f057ead1e48b17fc04/diagnostics/compute_diagnostics.jl#L83

**Comment by charleskawczynski** [comment]
@yairchn, the other `Δz`'s are being fixed in other PRs. Does this PR look okay?

**Review by yairchn — APPROVED** [review]

**Pull request merged**
