### PR TITLE
Additional data structs for snow

### PR DESCRIPTION
**Pull request by trontrytel**
The last of the peel offs from #506 Hopefully no changes as well. 🤞

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
LGTM. Sorry the tests are so brittle!

**Comment by trontrytel** [comment]
> LGTM. Sorry the tests are so brittle!

No worries! They are extremely useful!

I will regenerate and update the mse tables after I run it again with updated aux order. Then r+ 🌦️

**Comment by trontrytel** [comment]
Actually, I think the differences were only caused by the mse table changes from updated aux order. 🔥

**Pull request merged**
