### PR TITLE
update SSCF to 0.9

### PR DESCRIPTION
**Pull request by jbphyswx**
## Purpose 
Add dependency to force version 0.9 for SOCRATESSingleColumnForcings

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
I think you need to instantiate so that you incorporate manifest changes too

**Review by charleskawczynski — COMMENTED** [review]
I forget the environments in TC-- do we need to add this dep to more environments? cc @trontrytel

**Comment by trontrytel** [comment]
> I forget the environments in TC-- do we need to add this dep to more environments? cc @trontrytel

No, I think it's just the integration tests. I am re-trying the Ci now. I think buildkite failed randomly before, not because of this PR.

Btw, can you remind me what the UpDeps test is checking? I wonder why it is failing now, as we have just updated the deps?

**Comment by charleskawczynski** [comment]
> Btw, can you remind me what the UpDeps test is checking? I wonder why it is failing now, as we have just updated the deps?

https://github.com/CliMA/TurbulenceConvection.jl/pull/909#pullrequestreview-930773269

**Review by trontrytel — APPROVED** [review]

**Pull request merged**
