### PR TITLE
Apply theta-l bcs where it seems to be missing

### PR DESCRIPTION
**Pull request by charleskawczynski**
I'm hoping that this will fix the theta-L plots in our comparisons.

### CODE REVIEW

**Review by haakon-e — APPROVED** [review]
The plots look nice! 

Do you fix the same random seed for each simulation when test plots are created? That may be the cause of some small discrepancies too.

**Comment by charleskawczynski** [comment]
> The plots look nice! ... Do you fix the same random seed for each simulation when test plots are created? That may be the cause of some small discrepancies too.

Thanks :slightly_smiling_face:. There's currently no random seed, but we've [suppressed random numbers](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/utility_functions.jl#L5-L11) for now (and have TODOs to add them back in). I believe the small differences are due to the BCs being applied.

Hmm, I thought that some of the plots would be different. E.g., Bomex theta-L contours.

**Comment by haakon-e** [comment]
> > The plots look nice! ... Do you fix the same random seed for each simulation when test plots are created? That may be the cause of some small discrepancies too.
> 
> Thanks 🙂. There's currently no random seed, but we've [suppressed random numbers](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/utility_functions.jl#L5-L11) for now (and have TODOs to add them back in). I believe the small differences are due to the BCs being applied.
> 
> Hmm, I thought that some of the plots would be different. E.g., Bomex theta-L contours.

I only looked at TRMM, which failed.. But I can't see any difference in theta_l in Bomex. Are you saying that you'd expect a difference due to this change?

**Comment by charleskawczynski** [comment]
> I only looked at TRMM, which had the failed tests.. But I can't see any difference in theta_l in Bomex. Are you saying that you'd expect a difference due to this change?

Yeah, the contour plots look like solid planes. I just found out why, I think, though. The ICs for THL are not defined, so it exports zeros at t=0, which kind of ruins the contour plots. Trying it out now.

**Comment by charleskawczynski** [comment]
Yeah, that was it. Seems to look okay now. I had to add a if-branch in `compute_mse` for this anyway since the Artifacts still have uninitialized temperatures at t=0.

**Comment by charleskawczynski** [comment]
Forgot to update the tables.. bors r+

**Pull request merged**
