### PR TITLE
Remove `revxrange`

### PR DESCRIPTION
**Pull request by charleskawczynski**
I think that this is done correctly, note that we're not traversing the `term_vel[k] = terminal_velocity(Rain.C_drag, Rain.MP_n_0, QR.values[k], self.Ref.rho0_half[k])` in reverse order, since I don't think that should have any impact on the result.

### CODE REVIEW

**Comment by trontrytel** [comment]
> I think that this is done correctly, note that we're not traversing the `term_vel[k] = terminal_velocity(Rain.C_drag, Rain.MP_n_0, QR.values[k], self.Ref.rho0_half[k])` in reverse order, since I don't think that should have any impact on the result.

Not sure. The idea was to integrate the rain from top down because it is falling down and we are using upwind to do it

**Comment by charleskawczynski** [comment]
> Not sure. The idea was to integrate the rain from top down because it is falling down and we are using upwind to do it

We're still looping in reverse order in the loop below, I think the loop I changed the order on simply populates `term_vel`--it doesn't look like that loop depends on the order (unless it's for a simplified case, in which case I'm more than happy to keep it in reverse order).

**Review by trontrytel — APPROVED** [review]

**Comment by trontrytel** [comment]
> > Not sure. The idea was to integrate the rain from top down because it is falling down and we are using upwind to do it
> 
> We're still looping in reverse order in the loop below, I think the loop I changed the order on simply populates `term_vel`--it doesn't look like that loop depends on the order (unless it's for a simplified case, in which case I'm more than happy to keep it in reverse order).

You are right. I think this should be ok

**Pull request merged**
